openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
paths:
  /user/current-amount:
    put:
      summary: Update current balance
      operationId: updateCurrentAmount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: The new starting capital amount in Euros
              required:
                - amount
      responses:
        '200':
          description: Balance updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: integer
